apply:
	terraform apply -auto-approve
destroy:
	#terraform destroy
	# terraform apply -destroy           
	terraform apply -destroy  -auto-approve

validate:
	terraform validate
plan:
	terraform plan

init:
	terraform init
