name: Infra Terraform Apply

on:
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') &&
        startsWith(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      - name: Get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branchname=$(curl -H "Authorization: token ${GITHUB_TOKEN}" \
            ${{ github.event.issue.pull_request.url }} | jq -r '.head.ref')
          echo "branchname=$branchname" >> $GITHUB_OUTPUT

      - name: Checkout upstream branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}

      - name: zip python code
        run: |
          zip -r ./python_lambda.zip handler.py r2.py python/* ipam.ttf invoice_generator.py
          mkdir -p ../../infra/environments/prod/lambda
          mv ./python_lambda.zip ../../infra/environments/prod/lambda/python_lambda.zip
        working-directory: pdf_generate/src

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra/environments/prod

      - name: Apply Terraform
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          WEB_BASE_URL: ${{ secrets.WEB_BASE_URL }}
          FONT_NAME: ${{ secrets.FONT_NAME }}
          FONT_PATH: ${{ secrets.FONT_PATH }}
        run: |
          terraform apply -auto-approve \
            -var "slack_token=${SLACK_TOKEN}" \
            -var "slack_client_id=${SLACK_CLIENT_ID}" \
            -var "slack_client_secret=${SLACK_CLIENT_SECRET}" \
            -var "session_secret=${SESSION_SECRET}" \
            -var "web_base_url=${WEB_BASE_URL}" \
            -var "font_name=${FONT_NAME}" \
            -var "font_path=${FONT_PATH}"
        working-directory: infra/environments/prod
