name: Incra API Server Terraform Apply

on:
  issue_comment:
    types: [created]


# permissions:
#   contents: read
#   pull-requests: write

jobs:
  terraform-apply:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Checkout upstream branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FONT_NAME: ${{ secrets.FONT_NAME }}
          FONT_PATH: ${{ secrets.FONT_PATH }}
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_REGION_NAME: ${{ secrets.R2_REGION_NAME }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          terraform apply -auto-approve \
            -var "access_key"="${AWS_ACCESS_KEY}" \
            -var "secret_key"="${AWS_SECRET_ACCESS}" \
            -var "region"="${AWS_REGION}" \
            -var "font_name=${FONT_NAME}" \
            -var "font_path=${FONT_PATH}" \
            -var "r2_endpoint_url=${R2_ENDPOINT_URL}" \
            -var "aws_access_key_id=${R2_ACCESS_KEY_ID}" \
            -var "aws_secret_access_key=${R2_SECRET_ACCESS_KEY}" \
            -var "region_name=${R2_REGION_NAME}" \
            -var "bucket_name=${BUCKET_NAME}"
        working-directory: pdf_generate/terraform

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const comment = `Terraform Apply has been executed successfully. ✅`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
