name: Incra API Server Terraform Apply

on:
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write 
  contents: read

jobs:
  terraform-apply:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      - name: Get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branchname=$(curl -H "Authorization: token ${GITHUB_TOKEN}" \
            ${{ github.event.issue.pull_request.url }} | jq -r '.head.ref')
          echo "branchname=$branchname" >> $GITHUB_OUTPUT

      - name: Checkout upstream branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: pdf_generate/terraform

      - name: Apply Terraform
        env:
          FONT_NAME: ${{ secrets.FONT_NAME }}
          FONT_PATH: ${{ secrets.FONT_PATH }}
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_REGION_NAME: ${{ secrets.R2_REGION_NAME }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          terraform apply -auto-approve \
            -var "font_name=${FONT_NAME}" \
            -var "font_path=${FONT_PATH}" \
            -var "r2_endpoint_url=${R2_ENDPOINT_URL}" \
            -var "aws_access_key_id=${R2_ACCESS_KEY_ID}" \
            -var "aws_secret_access_key=${R2_SECRET_ACCESS_KEY}" \
            -var "region_name=${R2_REGION_NAME}" \
            -var "bucket_name=${BUCKET_NAME}"
            -var "aws_account_id=${AWS_ACCOUNT_ID}"
        working-directory: pdf_generate/terraform

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const comment = `Terraform Apply has been executed successfully. ✅`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
