name: Incra API Server Terraform Apply

on:
  issue_comment:
    types: [created]


# permissions:
#   contents: read
#   pull-requests: write

jobs:
  terraform-apply:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest

    steps:
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Checkout upstream branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_font_name: ${{ secrets.FONT_NAME }}
          TF_VAR_font_path: ${{ secrets.FONT_PATH }}
          TF_VAR_r2_endpoint_url: ${{ secrets.R2_ENDPOINT_URL }}
          TF_VAR_aws_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TF_VAR_region_name: ${{ secrets.R2_REGION_NAME }}
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const comment = `Terraform Apply has been executed successfully. ✅`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
